name: epoxpy_env
channels:
- mosdef
- omnia
- conda-forge
- glotzer
- cmelab
- defaults
dependencies:
- python=3.5
- numpy
- freud
- matplotlib
- hoomd_dybond
- gsd
- pytest
- pytest-cov
- coverage>=4.4
- pluggy>=0.7
- coveralls
- PyYAML
- signac
- signac-flow
- pip:
  - "git+https://github.com/mikemhenry/mbuild.git@mike/plankton"
