#!/bin/bash

#SBATCH -J expoxpy-test
#SBATCH -o log_epoxypy_test.o%j
#SBATCH -n 28
#SBATCH --cpus-per-task=1
#SBATCH -p shortq
#SBATCH -t 1:00:00

# Abort the script on error
set -e
set -o pipefail

# Remove any previously loaded modules
module purge

# Load modules
module load slurm
module load gcc/7.2.0
module load cmake
module load anaconda/anaconda3/5.1.0 

module list

echo "Activating python environment"
source activate enterprise

# Load the configuration so we know where the source code is
source ~/hoomd_blue_group8/enterprise.incl
echo "Old Python Path: $PYTHONPATH"
export PYTHONPATH="$PYTHONPATH:${HOOMD_DIR}/build"
echo "New Python Path: $PYTHONPATH"

echo "Moving to epoxpy directory: $EPOXPY_DIR"
cd $EPOXPY_DIR

echo "Running pip install ."
pip install .

echo "Starting tests"
pytest
echo "Done!"
