python:
    - 2.7
    - 3.5
    - 3.6
cuda:
    - 8.0
    - 7.5

pin_run_as_build:
    cudatoolkit:
        max_pin: x.x

ignore_version:
    - numpy
    - mpich2
    - cmake
    - pkg-config
    - sqlite
